version: '3.9'

services:

  db:
    image: postgres:16.2-bullseye # we are using specific bullseye image for minimal DB size
    restart: always
    container_name: database
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - ./dockerConfig.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - ${DB_PORT_FOR_BACKEND}
    networks:
      - backend_network

  backend:
    build:
      context: ./RealTimeSensorDataAnalyticsBackend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./dockerConfig.env
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - db
    expose:
      - 8080


  frontend:
    build:
      context: ./sensor_analytics_frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./dockerConfig.env
    container_name: analytics_frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - frontend_network
      - backend_network
    expose:
      - ${FRONTEND_PORT}
    depends_on:
      - db
      - backend

  activemq:
    image: apache/activemq-artemis:latest-alpine
    restart: always
    container_name: activemq
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - ./dockerConfig.env
    volumes:
      - ./database/mqtt:/var/lib/artemis-instance
    ports:
      - 61616:61616 # 1883:1883
      - 8161:8161
    expose:
      - 8161
      - 61616
    networks:
      - backend_network
    depends_on:
      - db

  # zookeeper:
  #   image: wurstmeister/zookeeper:latest
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - backend_network

  # kafka:
  #   image: wurstmeister/kafka:latest
  #   ports:
  #     - "9092:9092"
  #   expose:
  #     - "9093"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "${KAFKA_TOPIC_NAME_INTIAL}:1:1"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - backend_network

# volumes:
#   pgdata:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: ./pgdata

networks:
  backend_network:
  frontend_network: